-- MySQL Script generated by MySQL Workbench
-- Sat Feb 18 20:02:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bosdos6qw6vefrichu88
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bosdos6qw6vefrichu88` ;

-- -----------------------------------------------------
-- Schema bosdos6qw6vefrichu88
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bosdos6qw6vefrichu88` DEFAULT CHARACTER SET utf8 ;
USE `bosdos6qw6vefrichu88` ;

-- -----------------------------------------------------
-- Table `bosdos6qw6vefrichu88`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosdos6qw6vefrichu88`.`Autor` ;

CREATE TABLE IF NOT EXISTS `bosdos6qw6vefrichu88`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `Nombre_autor` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Breve_biografia` MEDIUMTEXT NOT NULL,
  `Activo` BIT(1) NULL DEFAULT b'1',
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bosdos6qw6vefrichu88`.`Continente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosdos6qw6vefrichu88`.`Continente` ;

CREATE TABLE IF NOT EXISTS `bosdos6qw6vefrichu88`.`Continente` (
  `idContinente` INT NOT NULL AUTO_INCREMENT,
  `Nombre_continente` VARCHAR(45) NOT NULL,
  `Mapa` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`idContinente`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bosdos6qw6vefrichu88`.`Estilos_pintura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosdos6qw6vefrichu88`.`Estilos_pintura` ;

CREATE TABLE IF NOT EXISTS `bosdos6qw6vefrichu88`.`Estilos_pintura` (
  `idEstilos_pintura` INT NOT NULL AUTO_INCREMENT,
  `Nombre_estilo` VARCHAR(45) NOT NULL,
  `Descripcion_estilo` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idEstilos_pintura`),
  UNIQUE INDEX `idEstilos_pintura_UNIQUE` (`idEstilos_pintura` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bosdos6qw6vefrichu88`.`Pintura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosdos6qw6vefrichu88`.`Pintura` ;

CREATE TABLE IF NOT EXISTS `bosdos6qw6vefrichu88`.`Pintura` (
  `idPintura` INT NOT NULL AUTO_INCREMENT,
  `Nombre_pintura` VARCHAR(45) NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  `Continente_idContinente` INT NOT NULL,
  `Estilos_pintura_idEstilos_pintura` INT NOT NULL,
  `year_elaboracion` INT NOT NULL,
  `numero_piezas` INT NOT NULL,
  `pintura_img` LONGBLOB NULL DEFAULT NULL,
  `Descripcion_pintura` MEDIUMTEXT NOT NULL,
  `ruta_interna_server` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`idPintura`),
  INDEX `fk_Pintura_Autor_idx` (`Autor_idAutor` ASC) VISIBLE,
  INDEX `fk_Pintura_Continente1_idx` (`Continente_idContinente` ASC) VISIBLE,
  INDEX `fk_Pintura_Estilos_pintura1_idx` (`Estilos_pintura_idEstilos_pintura` ASC) VISIBLE,
  CONSTRAINT `fk_Pintura_Autor`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `bosdos6qw6vefrichu88`.`Autor` (`idAutor`),
  CONSTRAINT `fk_Pintura_Continente1`
    FOREIGN KEY (`Continente_idContinente`)
    REFERENCES `bosdos6qw6vefrichu88`.`Continente` (`idContinente`),
  CONSTRAINT `fk_Pintura_Estilos_pintura1`
    FOREIGN KEY (`Estilos_pintura_idEstilos_pintura`)
    REFERENCES `bosdos6qw6vefrichu88`.`Estilos_pintura` (`idEstilos_pintura`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bosdos6qw6vefrichu88`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosdos6qw6vefrichu88`.`questions` ;

CREATE TABLE IF NOT EXISTS `bosdos6qw6vefrichu88`.`questions` (
  `idquestions` INT NOT NULL AUTO_INCREMENT,
  `pregunta_var` MEDIUMTEXT NOT NULL,
  `Pintura_idPintura` INT NOT NULL,
  PRIMARY KEY (`idquestions`),
  INDEX `fk_questions_Pintura1_idx` (`Pintura_idPintura` ASC) VISIBLE,
  CONSTRAINT `fk_questions_Pintura1`
    FOREIGN KEY (`Pintura_idPintura`)
    REFERENCES `bosdos6qw6vefrichu88`.`Pintura` (`idPintura`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bosdos6qw6vefrichu88`.`Respuestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosdos6qw6vefrichu88`.`Respuestas` ;

CREATE TABLE IF NOT EXISTS `bosdos6qw6vefrichu88`.`Respuestas` (
  `idRespuestas` INT NOT NULL AUTO_INCREMENT,
  `respuesta_var` MEDIUMTEXT NOT NULL,
  `Es_correcta` TINYINT NOT NULL,
  `questions_idquestions` INT NOT NULL,
  PRIMARY KEY (`idRespuestas`),
  INDEX `fk_Respuestas_questions1_idx` (`questions_idquestions` ASC) VISIBLE,
  CONSTRAINT `fk_Respuestas_questions1`
    FOREIGN KEY (`questions_idquestions`)
    REFERENCES `bosdos6qw6vefrichu88`.`questions` (`idquestions`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bosdos6qw6vefrichu88`.`mulitimedia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosdos6qw6vefrichu88`.`mulitimedia` ;

CREATE TABLE IF NOT EXISTS `bosdos6qw6vefrichu88`.`mulitimedia` (
  `idmulitimedia` INT NOT NULL,
  `Desceipcion` MEDIUMTEXT NOT NULL,
  `Guion` MEDIUMTEXT NOT NULL,
  `Archivo_reproducir` LONGBLOB NOT NULL,
  `Pintura_idPintura` INT NOT NULL,
  PRIMARY KEY (`idmulitimedia`),
  INDEX `fk_mulitimedia_Pintura1_idx` (`Pintura_idPintura` ASC) VISIBLE,
  CONSTRAINT `fk_mulitimedia_Pintura1`
    FOREIGN KEY (`Pintura_idPintura`)
    REFERENCES `bosdos6qw6vefrichu88`.`Pintura` (`idPintura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bosdos6qw6vefrichu88`.`puzzle_part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosdos6qw6vefrichu88`.`puzzle_part` ;

CREATE TABLE IF NOT EXISTS `bosdos6qw6vefrichu88`.`puzzle_part` (
  `idpuzzle_part` INT NOT NULL AUTO_INCREMENT,
  `Id_ubicacion_parte` INT NOT NULL,
  `parte` MEDIUMTEXT NOT NULL,
  `Pintura_idPintura` INT NOT NULL,
  PRIMARY KEY (`idpuzzle_part`),
  INDEX `fk_puzzle_part_Pintura1_idx` (`Pintura_idPintura` ASC) VISIBLE,
  CONSTRAINT `fk_puzzle_part_Pintura1`
    FOREIGN KEY (`Pintura_idPintura`)
    REFERENCES `bosdos6qw6vefrichu88`.`Pintura` (`idPintura`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
